routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\StripeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Products
Route::get('/', [ProductController::class, 'productList'])->name('products.list');
Route::resource('products', ProductController::class);
// Cart
Route::get('cart', [CartController::class, 'cartList'])->name('cart.list');
Route::post('cart', [CartController::class, 'addToCart'])->name('cart.store');
Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
Route::post('remove', [CartController::class, 'removeCart'])->name('cart.remove');
Route::post('clear', [CartController::class, 'clearAllCart'])->name('cart.clear');
// Stripe
Route::get('stripe', [StripeController::class, 'stripe'])->name('stripe');
Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
          <main class="my-8">
            <div class="container px-6 mx-auto">
                <div class="flex justify-center my-6">
                    <div class="flex flex-col w-full p-8 text-gray-800 bg-white shadow-lg pin-r pin-y md:w-4/5 lg:w-4/5">
                      @if ($message = Session::get('success'))
                          <div class="p-4 mb-3 bg-green-400 rounded">
                              <p class="text-green-800">{{ $message }}</p>
                          </div>
                      @endif
                        <h3 class="text-3xl text-bold">Cart contents</h3>
                      <div class="flex-1">
                        <table class="w-full text-sm lg:text-base" cellspacing="0">
                          <thead>
                            <tr class="h-12 uppercase">
                              <th class="hidden md:table-cell"></th>
                              <th id="name" >Name</th>
                              <th class="pl-5 text-left lg:text-right lg:pl-0">
                                <span id="quantity" class="hidden lg:inline">Quantity</span>
                              </th>
                              <th id="price" class="hidden text-right md:table-cell"> Price</th>
                              <th id="remove" class="hidden thmargin text-right md:table-cell"> Remove </th>
                            </tr>
                          </thead>
                          <tbody>
                              @foreach ($cartItems as $item)
                            <tr>
                              <td class="hidden pb-4 md:table-cell">
                                <a href="#">
                                  <img src="img/{{ $item->attributes->image }}" class="w-20 rounded" alt="Thumbnail">
                                </a>
                              </td>
                              <td>
                                  <p class="mb-2 md:ml-4">{{ $item->name }}</p>
                              </td>
                              <td class="justify-center mt-6 md:justify-end md:flex">
                                <div class="h-10 w-28">
                                  <div class="relative flex flex-row w-full h-8">

                                    <form action="{{ route('cart.update') }}" method="POST">
                                      @csrf
                                      <input type="hidden" name="id" value="{{ $item->id}}" >
                                    <input type="number" name="quantity" value="{{ $item->quantity }}"
                                    class="w-6 text-center bg-gray-300" />
                                    <button type="submit" class="up waves-effect waves-pink btn">update</button>
                                    </form>
                                  </div>
                                </div>
                              </td>
                              <td class="hidden text-right md:table-cell">
                                <span class="text-sm font-medium lg:text-base">
                                    {{ $item->price }} MAD
                                </span>
                              </td>
                              <td class="hidden text-right md:table-cell">
                                <form action="{{ route('cart.remove') }}" method="POST">
                                  @csrf
                                  <input type="hidden" value="{{ $item->id }}" name="id">
                                  <button><img class="trash" src="/img/trash.svg" alt="trash" width=100px /></button>

                              </form>

                              </td>
                            </tr>
                            @endforeach

                          </tbody>
                        </table>
                        <div class="container flow-text col s12">
                         Total: {{ Cart::getTotal() }} MAD
                        </div>
                        <div class="row">
                        <div class="col s6">
                          <form action="{{ route('cart.clear') }}" method="POST">
                            @csrf
                            <button class="px-6 py-2 text-red-800 bg-red-300">Remove All</button>
                          </form>
                        </div>


                        <div class="col s6">
                            {{-- Payment  --}}
                            <form method="get" action="{{ route('stripe')}}">
                              @csrf
                              <input type="hidden" name="amount" value="{{Cart::getTotal()}}" class="w-6 text-center bg-gray-300" />
                              <button class="btn green rounded-3 detail pay">Pay now ({{Cart::getTotal()}} MAD)</button>
                            </form>
                          </div>
                        </div>


                      </div>
                    </div>
                  </div>
            </div>
        </main>
    @endsection

resources/views/products.blade.php
@extends('layouts.app')

@section('content')

    <div class="container px-6 mx-auto">
        <h3 class="text-2xl product container font-medium text-gray-50">Product List</h3>
        <div class="row">
            @foreach ($products as $product)

            <div class="col-4">
                <div class="card">
                    <div class="card-image waves-effect waves-block waves-light">
                        <img class="materialboxed" height="400px" src='img/{{$product->image}}' alt="{{$product->image}}">
                    </div>

                    <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">{{$product->name}}</span>
                    <p class="price">{{$product->price}} MAD</p>
                    <form  method="POST" action="{{  route('cart.store')}}" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" value="{{ $product->id }}" name="id">
                        <input type="hidden" value="{{ $product->name }}" name="name">
                        <input type="hidden" value="{{ $product->price }}" name="price">
                        <input type="hidden" value="{{ $product->image }}"  name="image">


                        <input type="number" name="quantity" value=1
                               class="text-sm sm:text-base px-2 pr-2 rounded-lg border border-gray-400 py-1 focus:outline-none focus:border-blue-400 "
                               style="width: 50px"/>

                        <input type="hidden" id="id" name="id" value="{{ $product->id }}">
                        <button type="submit" class="ml-9 waves-effect waves-pink btn">
                            Add to Cart
                        </button>
                    </form>
                    </div>
{{--                     <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">Product description:<i class="material-icons right">close</i></span>
                    <p>{{$product->description}}</p>
                    </div> --}}
{{--                     <a href="{{ route('products.show', $product) }}" title="show description" >Show</a> --}}


                            <a class="white waves-effect waves-teal btn flow-text detail" href="{{ route('products.show', $product) }}" title="show description" >
                                Detail</a>


                </div>
            </div>
            @endforeach
        </div>
    </div>

@endsection

resources/views/show.blade.php
@extends("layouts.app")
@section("content")

<div class="container #e3f2fd blue lighten-5">
	<h1 class="#f48fb1 pink-text #e3f2fd blue lighten-5">{{ $product->name }}</h1>

	<div class="container flow-text col s12 card-panel" >{{ $product->description }}</div>

	<button class="white waves-effect waves-teal btn flow-text"><a class="pink-text hover:bg-violet-600 link" href="{{ url('/') }}" title="back to shop" >Back to Shop</a></button>

</div>


@endsection

resources/views/stripe.blade.php
<!DOCTYPE html>
<html>
   <head>
      <title>Payment Page</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
      <style type="text/css">
         .panel-title {
         display: inline;
         font-weight: bold;
         }
         .display-table {
         display: table;
         }
         .display-tr {
         display: table-row;
         }
         .display-td {
         display: table-cell;
         vertical-align: middle;
         width: 61%;
         }
      </style>
   </head>
   <body>
      <div class="container">

         <div class="row">
            <div class="col-md-6 col-md-offset-3">
               <h1>Payment Details <img src="/img/credit-card.svg" alt="credit-card" width=50px /></h1>

               <div class="panel panel-default credit-card-box">
                  <div class="panel-heading display-table" >
                     <div class="row display-tr" >
                        <h3 class="panel-title display-td" ></h3>
                     </div>
                  </div>
                  <div class="panel-body">
                     @if (Session::has('success'))
                     <div class="alert alert-success text-center">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        <p>{{ Session::get('success') }}</p>
                     </div>
                     @endif
                     <form
                        role="form"
                        action="{{ route('stripe.post') }}"
                        method="post"
                        class="require-validation"
                        data-cc-on-file="false"
                        data-stripe-publishable-key="{{ env('STRIPE_KEY') }}"
                        id="payment-form">
                        @csrf
                        <div class='form-row row'>
                           <div class='col-xs-12 form-group required'>
                              <label class='control-label'>Name on Card</label> <input
                                 class='form-control' size='4' type='text'>
                           </div>
                        </div>
                        <div class='form-row row'>
                           <div class='col-xs-12 form-group card required'>
                              <label class='control-label'>Card Number</label> <input
                                 autocomplete='off' class='form-control card-number' size='20'
                                 type='text'>
                           </div>
                        </div>
                        <div class='form-row row'>
                           <div class='col-xs-12 col-md-4 form-group cvc required'>
                              <label class='control-label'>CVC</label> <input autocomplete='off'
                                 class='form-control card-cvc' placeholder='ex. 311' size='4'
                                 type='text'>
                           </div>
                           <div class='col-xs-12 col-md-4 form-group expiration required'>
                              <label class='control-label'>Expiration Month</label> <input
                                 class='form-control card-expiry-month' placeholder='MM' size='2'
                                 type='text'>
                           </div>
                           <div class='col-xs-12 col-md-4 form-group expiration required'>
                              <label class='control-label'>Expiration Year</label> <input
                                 class='form-control card-expiry-year' placeholder='YYYY' size='4'
                                 type='text'>
                           </div>
                        </div>
                        <div class='form-row row'>
                           <div class='col-md-12 error form-group hide'>

                           </div>
                        </div>
                        <div class="row">
                           <div class="col-xs-12">
                            <input type="hidden" name="amount" value="{{Cart::getTotal()}}" class="w-6 text-center bg-gray-300" />
                              <button class="btn btn-primary btn-lg btn-block" type="submit">Pay Now ({{$request->amount}} MAD)</button>
                           </div>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </body>
   <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
   <script type="text/javascript">
      $(function() {
    var $form = $(".require-validation");
    $('form.require-validation').bind('submit', function(e) {
        var $form = $(".require-validation"),
            inputSelector = ['input[type=email]', 'input[type=password]',
                'input[type=text]', 'input[type=file]',
                'textarea'
            ].join(', '),
            $inputs = $form.find('.required').find(inputSelector),
            $errorMessage = $form.find('div.error'),
            valid = true;
        $errorMessage.addClass('hide');
        $('.has-error').removeClass('has-error');
        $inputs.each(function(i, el) {
            var $input = $(el);
            if ($input.val() === '') {
                $input.parent().addClass('has-error');
                $errorMessage.removeClass('hide');
                e.preventDefault();
            }
        });
        if (!$form.data('cc-on-file')) {
            e.preventDefault();
            Stripe.setPublishableKey($form.data('stripe-publishable-key'));
            Stripe.createToken({
                number: $('.card-number').val(),
                cvc: $('.card-cvc').val(),
                exp_month: $('.card-expiry-month').val(),
                exp_year: $('.card-expiry-year').val()
            }, stripeResponseHandler);
        }
    });
    function stripeResponseHandler(status, response) {
        if (response.error) {
            $('.error')
                .removeClass('hide')
                .find('.alert')
                .text(response.error.message);
        } else {
            /* token contains id, last4, and card type */
            var token = response['id'];
            $form.find('input[type=text]').empty();
            $form.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
            $form.get(0).submit();
        }
    }
});
   </script>
</html>